# schema.yml
version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: "Sales data"
        columns:
          - name: date_date
            description: "date of purchase"
          - name: orders_id
            description: "id of the order"
            tests:
              - not_null
          - name: pdt_id
            description: "product id"
            tests:
              - not_null
          - name: revenue
            description: "revenue of the product"
          - name: quantity
            description: "quantity of the product"
        tests:
          - unique:
              column_name: "(orders_id ||'_'|| pdt_id)"
              
      - name: product
        identifier: raw_product
        description: "Product data"
        columns:
          - name: products_id
            description: "id of the product"
            tests:
              - unique
              - not_null
              #tests for unique identifier/primary key
          - name: purchSE_price
            description: "purchase price of the order"
          - name: pdt_id
      - name: ship
        identifier: raw_ship
        description: "Shipping data"
        columns:
          - name: orders_id
            description: ID associated with order
          - name: shipping_fee
            description: shipping fee
          - name: log_cost
            description: logistic cost
          - name: ship_cost
            description: shipping cost
