# schema.yml
version: 2

sources:
  - name: raw
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: "Sales data"
      - name: product
        identifier: raw_gz_product
        description: "Product data"
      - name: ship
        identifier: raw_gz_ship
        description: "Shipping data"